default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: train_tracks_development

test:
  <<: *default
  database: train_tracks_test

production:
  <<: *default
  database: train_tracks_development
