# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Track.create(spotify_artist_name: "Taylor Swift", spotify_track_name: "Shake It Off", avg_bpm: 190, length: 300)
Track.create(spotify_artist_name: "Carly Rae Jepsin", spotify_track_name: "Call Me Maybe", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "BassNectar", spotify_track_name: "Techno", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "Bruno Mars", spotify_track_name: "Uptown Funk", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "RaeLynn", spotify_track_name: "God Made Girls", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "1", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "2", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "3", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "4", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "5", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "6", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "7", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "8", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "9", avg_bpm: nil, length: 300)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "10", avg_bpm: nil, length: 300)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "11", avg_bpm: nil, length: 300)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "12", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "13", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "14", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "15", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "KidsBop", spotify_track_name: "16", avg_bpm: nil, length: 500)

Track.create(spotify_artist_name: "Justin Bieber", spotify_track_name: "Baby", avg_bpm: 90, length: 200)
Track.create(spotify_artist_name: "ABBA", spotify_track_name: "Dancing Queen", avg_bpm: nil, length: 220)
Track.create(spotify_artist_name: "P!NK", spotify_track_name: "Sober", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Imagine Dragons", spotify_track_name: "I Bet My Life", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "FUN!", spotify_track_name: "We Are Young", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "1", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "2", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "3", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "4", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "5", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "6", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "7", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "8", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "9", avg_bpm: nil, length: 300)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "10", avg_bpm: nil, length: 300)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "11", avg_bpm: nil, length: 300)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "12", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "13", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "14", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "15", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "Cozy Chirs", spotify_track_name: "16", avg_bpm: nil, length: 500)


Track.create(spotify_artist_name: "Miley Cyrus", spotify_track_name: "The Climb", avg_bpm: 1, length: 200)
Track.create(spotify_artist_name: "James Blunt", spotify_track_name: "Beautiful", avg_bpm: nil, length: 175)
Track.create(spotify_artist_name: "Lionel Richie", spotify_track_name: "Hello", avg_bpm: nil, length: 220)
Track.create(spotify_artist_name: "The Fray", spotify_track_name: "How to Save a Life", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "James Bay", spotify_track_name: "Let It Go", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "1", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "2", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "3", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "4", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "6", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "7", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "8", avg_bpm: nil, length: 190)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "9", avg_bpm: nil, length: 300)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "10", avg_bpm: nil, length: 300)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "11", avg_bpm: nil, length: 300)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "12", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "13", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "14", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "15", avg_bpm: nil, length: 500)
Track.create(spotify_artist_name: "Yolo Body Bop", spotify_track_name: "16", avg_bpm: nil, length: 500)
